<script setup>
import Disclaimers from "../components/Disclaimers.vue";
import { onMounted, nextTick } from "vue";
import { useRoute } from "vue-router";

const route = useRoute();

onMounted(async () => {
	await nextTick();
	if (route.hash === "#privacy") {
		const element = document.getElementById("privacy");
		if (element) {
			element.scrollIntoView({ behavior: "smooth" });
		}
	}
});
</script>

<template>
	<div id="privacy">
		<h2>Privacy Policy</h2>
		<h3>User Accounts &amp; Authentication</h3>
		<p>
			When you create an account on our website, we collect your email address solely for account security and spam prevention. To
			finalize your login, our system automatically sends a secure verification code to your email. We do not use your registration
			email for marketing purposes, nor do we sell or share it with third parties.
		</p>
		<h3>Contact Form Submissions</h3>
		<p>
			If you choose to reach out to us using our contact form, we collect your name and email address to respond to your specific
			inquiry. We only use this information to communicate directly with you regarding your message. Submitting a contact form will
			not sign you up for unsolicited marketing newsletters.
		</p>
		<h3>How We Use Google Analytics</h3>
		<p>
			We use Google Analytics to help understand how visitors engage with our website. This service uses cookies to collect standard
			internet log information and visitor behavior information in an anonymous form. The information generated by the cookie about
			your use of the website (including IP address) is transmitted to Google. This information is then used to evaluate visitors&#39;
			use of the website and to compile statistical reports on website activity for us.
		</p>
		<p>
			We do not use Google Analytics to track, collect, or match any personally identifiable information of our visitors. If you wish
			to opt out of Google Analytics tracking on all websites, you can download and install the official
			<a href="https://support.google.com/analytics/answer/181881" target="_blank">Google Analytics Opt-out Browser Add-on</a> You can
			also learn more about how Google safeguards your data by visiting the
			<a href="https://policies.google.com/technologies/partner-sites" target="_blank">Google Privacy &amp; Terms page</a>.
		</p>
		<Disclaimers />
	</div>
</template>

<style scoped>
#privacy {
	color: #222;
	background-color: rgb(219 221 247 / 80%);
	border-radius: 8px;
	margin: 30px auto 0;
	padding: 15px 30px;
	width: fit-content;
}

h1,
h2 {
	text-align: center;
}

h3 {
	margin-top: 15px;
	text-transform: uppercase;
}
</style>
